### ISSUE TITLE
基于antd 4.0-bate0 有一个Dome实现了虚拟滚动

### ISSUE THREAD

**Issue by Nokecy** [yiyizym/infinite_table#1]

**Comment by yiyizym** [comment]
Dome ???

我也有关注这事。

目前 antd 通过引入 react-window 的方式实现虚拟滚动，Demo 中暴露很多实现细节，还有很多 bug 和功能缺陷（比如行高需固定）。

建议你看看这个实现 https://github.com/wubostc/virtualized-table-for-antd
